### ISSUE TITLE
View Community Information Page

### ISSUE THREAD

**Issue by xiningchen** [SENG513/Frontend#21]
- When a user clicks on a community, they see a bunch of memes from that community. So why are we asking communities to fill out description text when people don't see it? We also don't have an update community information page... I'm a bit confused how communities work. 
- Also how is NSFW flag going to be displayed? 
- Do we need a PG thing where if you're under a certain age... a popup shows up or prevents you from browsing that community?

**Comment by Step7750** [comment]
I think we could have a expandable area on the sidebar when you're browsing a community to see its description, side bar text etc...

I think a prompt for NSFW communities is best.

**Comment by Step7750** [comment]
Now that I think of it though, how often would you see NSFW memes? I think the vast majority are safe and swearing in the meme is generally not regarded as NSFW.

**Comment by xiningchen** [comment]
- I don't understand what you mean by prompt for NSFW
- Does the NSFW have a label that shows up in the navigation bar?
- If description is in the side bar stuff, what's the difference between description and side bar text?
- I think we need to be careful of how much information we display on the side navigation... Even expanded the width is not very wide. I think it looks bad if it expands and becomes a mini wall of text... 
- Lol... Idk, just because we don't look at NSFW memes doesn't mean they don't exist. I think if it's easy enough for us to support it, it's best to keep that option. But I'm not sure how difficult/easy it is.

**Comment by Step7750** [comment]
* By prompt, I meant that when someone clicks on the NSFW community, it will show a dialog indicating whether they _really_ want to go there.
* I think there should be a able for it on the nav bar.
* Description could be used for some other ways in the site in the future in the UI when browsing (and could be indexed for searching). Ex. If you hover over a community name that someone posts in a comment, it could make a tooltip with the description.
* I agree, that's why I hope to support markdown so people could make tables, lists, etc... and make it less cluttered.
* Yeah, since there isn't too much work in implementing it, it also gives some cover to allow freedom while also ensuring it doesn't impact the average user.

**Comment by xiningchen** [comment]
Sounds good to me.
